### ISSUE TITLE
Incorrect import paths in feature modules in sub-directories.

### ISSUE THREAD

**Issue by Ferroin** [niksy/modernizr-esm#6]
Put simply, all the feature modules that are in sub-directories (for example, the various worker and es5/es6 feature modules) are trying to import things from `../src` when they should be trying to import from `../../src`.  This causes them to not load correctly in the browser or when being bundled into another application's build, making them essentially unusable.

**Comment by niksy** [comment]
@Ferroin you’re right, fixed in latest version!
