### ISSUE TITLE
TypeError: Modernizr[featureNameSplit[0]] is undefined

### ISSUE THREAD

**Issue by langalex** [niksy/modernizr-esm#7]
Starting with version 1.4, I'm getting this error when importing inputtypes: 

```js
import inputtypes from 'modernizr-esm/feature/inputtypes';
```

Error:

```js
TypeError: Modernizr[featureNameSplit[0]] is undefined
```

The error happens in `addTestResult()` in this line:

```js
Modernizr[featureNameSplit[0]][featureNameSplit[1]] = result;
```

`Modernizr` at this point is just an empty object, causing the asignment of `[featureNameSplit[1]` to fail as `Modernizr[featureNameSplit[0]]` is undefined.

This works up until version 1.3.1.

**Comment by niksy** [comment]
Good catch! `inputtypes` wasn’t added as object-like property in original package so I had to do some code adjustments in build process.

This also means that it’s more aligned with other features with multiple tests like `audio`, so there is [no more default export, only named exports](https://github.com/niksy/modernizr-esm/blob/master/feature/inputtypes.js#L39-L52).

Published as 1.7.0! 🎉
