### ISSUE TITLE
No export for webp detection

### ISSUE THREAD

**Issue by robdekort** [niksy/modernizr-esm#8]
Hi there! I'd like to use your package to detect webp support, but it seems the webp detect doesn't export anything.

**Comment by niksy** [comment]
@robdekort you’re right, thanks for the heads up! I’ve made the changes pushed in new major version because now we use proper ESM implementation with `exports` field. Check to see if this works for you!

**Comment by robdekort** [comment]
Hi @niksy. I’ve found another solution to my problem, but glad to hear this was helpful 👍.
